name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.2
        with:
          required-ros-distributions: noetic
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2
        with:
          package-name: basics_ros
          target-ros1-distro: noetic