name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.2 
        with:
          required-ros-distributions: noetic
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: basic_roscpp basic_rospy
          target-ros1-distro: noetic
      - name: lint
        run: |
          cd catkin_ws
          catkin build $(catkin list --depends-on roslint -u) --no-status --no-deps --catkin-make-args roslint
          LINT_CFG="-W2 --error unsorted_list --ignore uninstalled_script --error launch_depend --error description_meaningless"
          catkin_lint src $LINT_CFG
