name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.2 
        with:
          required-ros-distributions: noetic
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2 ros-tooling/action-ros-lint@master
        with:
          package-name: basic_roscpp basic_rospy
          target-ros1-distro: noetic
